%This function opens menus to recieve from the user the contents of the
%structure userData and the files with the extention ttr that will be
%analysed. Display a wait bar and show the movie that it's being analysed.
%Analyse the movies using the data generated by the LoadFiles and analyseData
%functions. Saves the results of all molecules as 3 files with the 
%extentions _res.txt, _trace.txt and _FRETonly_trace.txt. Returns the final
%results as the matrix trace_report trace_sheet and FRET_only_trace_sheet.
function  [trace_report trace_sheet FRET_only_trace_sheet] = checkall()
trace_report = [];
trace_sheet = [];
FRET_only_trace_sheet = [];
userData = menu_fret_analysis();
[control.file control.path] = getLongFiles('*.ttr');

if ischar(control.path)
    bar = waitbar(0,'Please wait');
    for nfile=1:numel(control.file)
        disp(['Analyzing "' control.file{nfile} '"...']);
        title('','Interpreter','none');
        waitbar(nfile/numel(control.file), bar, strcat('Analyzing ', ...
            control.file{nfile}));
        [data control analysis]= LoadFiles(control, userData,nfile);
        auxIndex = findstr(control.file{nfile},'_th');
        if isempty(auxIndex)
            auxIndex = findstr(control.file{nfile},'.');
        end
        auxStr = control.file{nfile}(1:auxIndex-1);
        if auxStr
            auxPos = findstr(auxStr, '_');
            auxPos = auxPos(end)+1;
            videoNumber = str2num(auxStr(auxPos:end));
            if isnan(videoNumber);
                videoNumber = nfile;
            end
        else
            videoNumber = nfile;
        end
        
        for nMol=1:control.totalMolecules
            if analysis.goodMolecules(nMol)
                mData = InimData(data, userData, nMol);
                FRETIndex = analysis.allIndex{nMol};
                regions{1} = 1:FRETIndex(1)-1; %pre_FRET_region
                regions{2} = FRETIndex(1):FRETIndex(2); %FRET_region
                regions{3} = FRETIndex(2)+1:FRETIndex(3)-1; %post_FRET_region
                regions{4} = FRETIndex(3):FRETIndex(4); %donor_only_region
                regions{5} = FRETIndex(4)+1:length(data.time); %post_donor_only_region
                [result trace FRET_only_trace] = analyseData(mData, data.time, ...
                    userData ,regions);

                result = cell2mat(struct2cell(result));
                traceCell = struct2cell(trace);
                trace = [];
                for j = 1:numel(traceCell)
                    trace = [trace,traceCell{j}];
                end
                FRET_only_trace = cell2mat(FRET_only_trace);
                
                %appends result to the list adding the video and molecule
                %number
                trace_report = [trace_report;videoNumber nMol result']; 
                trace_sheet = [trace_sheet;videoNumber*ones(size(trace,1),1)...
                    nMol*ones(size(trace,1),1) trace];
                FRET_only_trace_sheet = [FRET_only_trace_sheet; ...
                    videoNumber*ones(size(FRET_only_trace,1),1) ...
                    nMol*ones(size(FRET_only_trace,1),1) FRET_only_trace];
            end
        end
        disp(['Finish "' control.file{nfile} '"...']);
    end
    close(bar);
    if size(trace_report,1) == 0; % at the last trace and not a single one was selected
        disp('No traces selected');
    else
        filename = [control.path, control.file{1}];
        save_name = filename(1:findstr(filename,'_th')-1);
        if isempty(save_name)
            save_name=filename(1:findstr(filename,'.')-1);
        end
        auxNum = findstr(save_name,'_');
        if ~isempty(auxNum) 
            save_name = save_name(1:(auxNum(end)-1));
        end
        if userData.filter == 1
            dummy = 'medfilt';
        elseif userData.filter == 2;
            dummy = 'smooth';
        end
        
        save_name_report = strcat(save_name,'_',dummy, ...
            num2str(userData.smoothwidth),'_res.txt');
        [path file] = uiputfile('*.txt','Save as', save_name_report);

        if path ~= 0
            save_name = [file path];
            save_name = save_name(1:findstr(save_name,'_res.txt')-1);
            save_name_report = strcat(save_name,'_res.txt');
            save_name_trace = strcat(save_name,'_trace.txt');
            save_name_FRET_only_trace = strcat(save_name, '_FRETonly_trace.txt');

            save(save_name_report,'trace_report','-ASCII');
            save(save_name_trace,'trace_sheet','-ASCII');
            save(save_name_FRET_only_trace, 'FRET_only_trace_sheet','-ASCII');
        end
    end
end